### ISSUE TITLE
Missing Model_save256B file

### ISSUE THREAD

**Issue by taylorgaines** [jmyszewski/GANBioBERTMetaAnalysis#1]
Hi,

I was curious as to whether the GAN-BioBERT model was intentionally removed from the repo. Was it supposed to be?

**Comment by jmyszewski** [comment]
Thank you for bringing this to my attention; There were some issues uploading the saved model due to size; this should be rectified on the master branch now, you will need to unzip the file to use the saved model.

**Comment by taylorgaines** [comment]
when downloading the zipped file, it still does not have the model_save256B. when you unzip it, it just includes the rest of the project
